FROM nodefactory/nodejs-ts-starter:latest

RUN yarn run build

FROM node:carbon-alpine

RUN apk add --update  git build-base libgit2-dev && \
  rm -rf /tmp/* /var/cache/apk/*

RUN ln -s /usr/lib/libcurl.so.4 /usr/lib/libcurl-gnutls.so.4

WORKDIR /app

COPY --from=0 /usr/app/dist/src /app
COPY --from=0 /usr/app/package.json /app/
COPY --from=0 /usr/app/yarn.lock /app/

RUN yarn install --frozen-lockfile --production && yarn cache clean

CMD ["node", "index.js"]
